### ISSUE TITLE
Works on PB632 with some issues

### ISSUE THREAD

**Issue by martin5233** [JuanJakobo/Pocketbook-Nextcloud-Client#1]
I tried out your Nextcloud connector and it kind of works on my PB632 (Touch HD3). I could see the first page of entries from my Nextcloud folder, but I wasn't able to download anything or scroll to the next page. I received a "An unknown error occurred" multiple times. Keep up the good work and let me know, if I can help. I'm a professional C++ developer myself, but I have not done anythink on Pocketbooks yet.

**Comment by JuanJakobo** [comment]
Hey @martin5233, thanks for the kind words. The release version is rather old. I uploaded a new one, that should work better. [(release 0.2)](https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.2) Currently I am implementing an algorithm to compare changed made on the PB file system to the nextcloud instance. If you find other features that are missing, please tell me.I am new to big  C++ world, so if you have any feedback on the code, it is appreciated. If you have plans to create something for the PB I am happy to answer questions. :)

**Comment by martin5233** [comment]
Hi @JuanJakobo, thanks for your quick response. I will try out your new version and take a look at the source code. Maybe we can get this to a useful state, I was looking for a way to get books onto the PB without having to use either a cable or the PB cloud. As I am hosting my own Nextcloud instance anyway, this is how I stumbled across your project.

**Comment by martin5233** [comment]
Hi @JuanJakobo, I just tried out your new release version 0.3. It works much better than the previous one. I can scroll through the entries in my Nextcloud folder by clicking on the page counter in the bottom right corner without problems. However, when I click onto one of the entries, I get a message "Check network connection", then "An unknown error occurred" and finally "Could not download....". The log file contains messages about starting the download, but it seems to crash, before it is finished. The nextcloud folder contains files with the attempted downloads, but always with zero size.
I also noticed another minor issue: It seems that the character encoding is not correct, some filenames have percent-encoded values like %2b in them, which is the ASCII code for '+'. I guess you have to decode the HTML-encoded filenames before displaying them.

**Comment by JuanJakobo** [comment]
Hi @martin5233, I uploaded a new version. [(0.31)](https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.31) 
I looked up the file rights and they seem to be alright. Therefore I made small changed to the curl process, but I am not sure if they will solve the problem. Unfortunately I can not reproduce the error, for me it works fine...
Anyway I also added the curl response code to the error message, would be really nice if you could provide it, than the error might be clearer. 
If this does not help it would really help me, if you could test the application with my nextcloud instance, as I dont have problems. I would create an test user and send you the credentials via email. You can find my email in my github profile.
Thanks for testing and have a nice weekend.

**Comment by JuanJakobo** [comment]
Problem solved by [Release 0.4](https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.4)
