### ISSUE TITLE
Login to nextcloud with LDAP

### ISSUE THREAD

**Issue by cmusik** [JuanJakobo/Pocketbook-Nextcloud-Client#11]
My nextcloud instance is using LDAP to authenticate users. The default setting with LDAP is to use an uuid as the internal username. So the path changes from https://url.com/remote.php/dav/files/username to https://url.com/remote.php/dav/files/uuid

Right now only the username scheme is supported. It would be great if I could enter the whole URL, but then the field is too short for my 17 char domain.

**Comment by JuanJakobo** [comment]
So just the username changes or?
The login takes the URL, (e.g. https://url.com) than adds  "/remote.php/dav/files/" and the username. (e.g. test

Therefore if you put the uuid into the username field, it should work fine.  Or am I misunderstand something? :)

**Comment by cmusik** [comment]
Login username is still the normal username. But in the URL the uuid is used. It is documented in the expert settings: https://docs.nextcloud.com/server/21/admin_manual/configuration_user/user_auth_ldap.html?highlight=ldap#expert-settings (see internal username)

**Comment by JuanJakobo** [comment]
In your example only the username is different. 
https://url.com/remote.php/dav/files/uuid
https://url.com/remote.php/dav/files/username
So from my point of view only the username changes. is the username field to small for the uuid?
I am sorry, but I am not really getting the problem. :sweat_smile:

**Comment by cmusik** [comment]
I still use a normal username (like cmusik) to login, but the internal username is different to my login name. E.g. in bigger installations this could be the email address. Then the internal username could be an uuid or something else. It depends on the configuration of nextcloud how the internal username looks like. And the webdav url is using the internal username.

**Comment by JuanJakobo** [comment]
Ah ok, therefore the root path changes. (not "https://url.com/remote.php/dav/files/" username, but the UUID)
So you want to login via username and password, but define the complete URL by yourself.
As of now you should be able to type in the 17 chars of the URL, but then the  "/remote.php/dav/files/" and the username will be added and therefore the login will fail.
I will add a algorithm that if "/remote.php/dav/files/" is already typed in, than it wont be added again. 
Hope I understood it now, thanks for the explanation. If I still did not get it correct, a small notification would be nice. :)

**Comment by cmusik** [comment]
One problem with that. It looks to me like the pocketbook keyboard can only enter 80 chars into one file. So perhaps you could also increase the limit. My URL with uuid is 84 chars :)

**Comment by JuanJakobo** [comment]
I implemented the login via https://url.com/remote.php/dav/files/uuid and increased the char number.
Could you please give it a try. :)

**Comment by cmusik** [comment]
It works (even on my IdeaPad 3 Pro :)) . Thanks a lot.

**Comment by JuanJakobo** [comment]
Great, if you find any other issues please create an new issue. :)
