### ISSUE TITLE
Add documentation howto build the app

### ISSUE THREAD

**Issue by cmusik** [JuanJakobo/Pocketbook-Nextcloud-Client#12]
I wanted to contribute, but I'm failing in finding out how to build the app. What SDK is used and which dependencies are needed. It would be great to have this information to allow developers to contribute and help you.

**Comment by JuanJakobo** [comment]
I added a segment on how to build in the readme. I am not sure if it covers all aspects, so  feedback is welcomed. 
Contributions are really appreciated.

**Comment by cmusik** [comment]
I will test it tommorrow and give you feedback. Thanks!

**Comment by cmusik** [comment]
With your documentation I was able to compile it. Thanks a lot!
