### ISSUE TITLE
Wrong version displayed under info

### ISSUE THREAD

**Issue by martin5233** [JuanJakobo/Pocketbook-Nextcloud-Client#13]
I just installed the latest version of your app on my Pocketbook. While trying to check, if it worked I noticed, that the displayed version number is not up to date, it seems to be fixed to 0.62 in the source code. Just a minor issue, but somewhat annoying, when you try to find out, which version you are actually using.

**Comment by JuanJakobo** [comment]
Hey @martin5233,

Thanks for the hint! I added it and will include it in a future release.

Did you find any other bugs using the new version? :)

**Comment by martin5233** [comment]
No, everything worked fine so far. Thanks for your great work.
