### ISSUE TITLE
An error occurs when changing to a folder (Curl Response Code 405)

### ISSUE THREAD

**Issue by WolfgangDpunkt** [JuanJakobo/Pocketbook-Nextcloud-Client#14]
I can access my Nextcloud and see the folder list of the root directory, but when accessing subfolders or trying to sync folders I get the following error:

`"An unknown error occured. Switching to offline modus. To work online turn on online modus in the menu. (Curl Response Code 405)"`

By the way many many thanks for the idea to develop this app, this would enable a very important feature!

**(PB Nextcloud Client 0.71; Nextcloud 21.0.3; Inkpad 3 Pro; Firmware U740-2.6.3.691)**

**Comment by JuanJakobo** [comment]
Hmm.. That error code says that the connection is not allowed, so I guess some redirecting is not working as it should. I uploaded an prebuild (https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.72), where I added a log entry for the URL. Below "Starting download of DataStructure" in the log file (placed in system/config/nextcloud/logfile.txt) your webdav URL should be displayed.

Could you please 
* Grap the URL and test if you can access it via the webbrowser of your computer (and if the URL changes once you reach your destination)
* send the schema that is used here, so I can identify if their is a format or redirection error
Mine looks like this
https://<URL>/remote.php/dav/files/<Username>/ --> for the root folder
https://<URL>/remote.php/dav/files/<Username>/Documents/ --> for the documents folder

Thanks for your feedback! :)

**Comment by WolfgangDpunkt** [comment]
Thank you for this quick and detailed answer!
I have tried some stuff, but the error remains.

This is the correct webdav-URL (which I typed into the client app on my ebookreader):
https://DOMAIN.de/CLOUDXY/remote.php/dav/files/USERNAME/ 
When tested via my webbrowser, it leads to an HTTP authentication request, after entering the login details, this  notice is displayed: 
"This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client"
So Nextcloud seems to be configured correctly.

As requested, I installed the new version and opened the log:

06/Jul/2021:18:06:02 +0200:Starting download of DataStructure
06/Jul/2021:18:06:02 +0200:https://DOMAIN.de/CLOUDXY/CLOUDXY/remote.php/dav/files/USERNAME/Documents/

So for some reason the folder name is doubled in the URL?
This address is of course wrong and nextcloud redirects me to the login home page when I test the address in the webbrowser.

When I look into the "nextcloud.cfg" (placed in system/config/), it looks correct:

UUID=USERNAME
password=$9.....
startFolder=/remote.php/dav/files/USERNAME/
url=https://DOMAIN.de/CLOUDXY
username=USERNAME

So there is no duplicate folder name (CLOUDXY) in the configuration file.
Thank you very much if you have any other idea.

**Comment by JuanJakobo** [comment]
Thanks for the detailed answer. :)

Seems to be the same issue as issue #1. There I just replaced the nextcloud/, so I guess your CLOUDXY/ is distinct. I added a method to remove everthing that is in front from /remote.php. 

Could you please try https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.72.

**Comment by WolfgangDpunkt** [comment]
Thank you so much for your great effort! That is super responsive and courteous.
That solved the problem, I can now open subdirectories and sync.
Great solution!

I don't want to seem too demanding, but I would have the next feature request right away: two-way synchronization #15
