### ISSUE TITLE
Feature request: two-way synchronization

### ISSUE THREAD

**Issue by WolfgangDpunkt** [JuanJakobo/Pocketbook-Nextcloud-Client#15]
I noticed that the sync only works as a download, new or changed files are downloaded from the server to the client, but not the other way around.

Is there a two-way synchronization planned? Can I upload changes to nextcloud as well? That would be extremely useful for annotations, notes and highlighting. I read a lot of scientific papers, for that it would be very important. 
But it's also handy for belltristic reading, because I can sort finished books e.g. into a folder "already read" or books I don't like into a folder "boring books".
That would be super handy.

Thanks again for the great support!

The PB Cloud and Dropbox both don't work very well and are questionable from a privacy perspective, so it's even more wonderful to have an independent alternative with your tool.

**Comment by WolfgangDpunkt** [comment]
Since this change may be more complex, I would like to sponsor it, via bountysource. With this, I would like to express my gratitude.
If that is ok for you?

**Comment by JuanJakobo** [comment]
I am not sure about this, but as far as I remember annotations, notes and highlights are not saved into the epub or pdf, but rather to an Pocketbook internal storage. When I tested they are saved to the notes app and from there can be exported as html to anywhere you wish. 

Are you using an other reader and would like to export the epubs/pdfs or the the exports from the notes app? 

The move feature is rather straight forward and I surely can implement it. :)

Thanks for the kind offer, but I started this project to learn C++ and currently doing it for fun. Therefore thanks, but currently not interested. :)

**Comment by WolfgangDpunkt** [comment]
Thank you very much for your kind response.
You are correct, the default app stores annotations in an internal database. But I use KOReader, it saves annotations, highlights and metadata as (sidecar) files, these could then be sychronized automatically.

But even if you use the default app and export the notes, it would be very handy if you could upload this HTML file directly to Nextcloud.

In general, it would be very desirable to have a way to get files out of the Pocketbook without having to plug in the USB cable or rely on Dropbox syncing.

Two-way synchronization really doesn't seem to be a self-evident feature, KOReader also only offers the download as a possibility for a cloud integration.

As a amateur, I imagine it to be relatively straightforward: A command that runs an rsync to synchronize the files between local or network accessible Nextcloud paths.

**Comment by WolfgangDpunkt** [comment]
Good news: I have successfully managed to install syncthing on my pocketbook. It does the job of file synchronization quite nicely.
If others want to try it too, here is a good tutorial:
https://thoughtpile.tastytea.de/posts/syncthing-on-pocketbook/

Maybe it can be combined with Nextcloud, but since syncthing runs on just about every device, I don't need really it anymore.

Good luck with the further development and thanks for the great support!
