### ISSUE TITLE
cacert.pem not recognized

### ISSUE THREAD

**Issue by JenswBE** [JuanJakobo/Pocketbook-Nextcloud-Client#18]
# Issue
App keeps telling me follow instructions to use a custom Cert Store. Even with the latest CA certificates from Mozilla.

I could provide a temporary account on my server if needed.

# Context
- Model: PocketBook HD3 (PB632)
- Firmware: U632.6.4.466
- App version: 0.73
- Firefox certs downloaded on: 1st of December 2021
- Nextcloud version: v22.2.3

Both app and certs are in folder `applications`:
![image](https://user-images.githubusercontent.com/6514515/144301756-66a60590-8682-4a7f-bd2f-1fd43047f163.png)

Error on reader:
![IMG_20211201_203348](https://user-images.githubusercontent.com/6514515/144302381-b42f8b43-6e63-461a-81fb-8dc5bef457b6.jpg)

Server certs are based on ISRG Root X1:
![image](https://user-images.githubusercontent.com/6514515/144302511-4db60c26-c577-48f3-8229-8ca3234d524d.png)

**Comment by Anrock** [comment]
This is weird. I'm using Nextcloud with Let's encrypt certs and didn't encounter this error. AFAIK for server address I used just the domain, without `/remote.php/...` part and it worked. Maybe try it?

**Comment by JenswBE** [comment]
Unfortunately same result:
![IMG_20211202_075545](https://user-images.githubusercontent.com/6514515/144373702-7f5ce0f7-6a6e-4252-94c6-3093d6c02434.jpg)

I also tried with my main account (`jens-ereader` has only read-only access on a single shared folder):
![image](https://user-images.githubusercontent.com/6514515/144373514-c59f0a90-6fa8-4355-ac81-35d84dec264f.png)

I can reproduce this issue as well with my primary Nextcloud server:
![image](https://user-images.githubusercontent.com/6514515/144373622-15c99f39-89c9-4b13-a83b-3835dea2e5ea.png)
![image](https://user-images.githubusercontent.com/6514515/144373662-a1a0b4ba-5576-4f83-a007-941b527c557f.png)

**Comment by JuanJakobo** [comment]
Hi, thanks for the detailed error explanation. A test user would help (github@johnnsen.tech), but I suppose that the error is located at the server. I at first had the issue that the certbot did not put the preferred keychain to the ISRG Root X1.  
`certbot certonly --apache -d www.yourdomain.com --preferred-chain "ISRG Root X1"` fixed it, but I suppose you already did that, or are you using nginx instead of apache?

One possible, but rather unsecure, solution would be to deactivate the SSL verification by adding following snipped to all curl functions (located in nextcloud.cpp) to the program:
`curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER,false);`

**Comment by JenswBE** [comment]
# Solution
Problem was indeed on server side. Seems I misunderstood the exact impact of the new chain of trust. You can find full details below.

@JuanJakobo could you please consider adding following command in the README to validate the correct chain is provided?
```bash
openssl s_client -showcerts -connect <HOSTNAME>:443 | grep Root
```

Thanks for the support!

# Details

Seems "View Certificate" in Firefox (and probably browsers in general) is not a valid way to check which certificate chain is used:
![image](https://user-images.githubusercontent.com/6514515/144508364-2824848e-1271-4c28-8dbc-e72a389863f0.png)
![image](https://user-images.githubusercontent.com/6514515/144508459-be863789-7681-4828-960e-89896839b85d.png)

But when calling `openssl` directly, you can see the "old" DST Root CA X3 certificate:
![image](https://user-images.githubusercontent.com/6514515/144508657-c1f58bb1-0bc9-4f99-9831-13b7af69f924.png)

Following resources really helped to understand the impact of the new chain of trust:
- https://community.letsencrypt.org/t/openssl-client-compatibility-changes-for-let-s-encrypt-certificates/143816
- https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

Finally, since I'm using Traefik as reverse proxy, I added a new certificate resolver to ensure I don't impact any other clients and used the resolver for the new proxy domain *-x1:
```yaml
      - "--certificatesresolvers.le-tls-x1.acme.tlsChallenge=true"
      - "--certificatesresolvers.le-tls-x1.acme.email=admin@example.com"
      - "--certificatesresolvers.le-tls-x1.acme.storage=/letsencrypt/acme-x1.json"
      - "--certificatesresolvers.le-tls-x1.acme.preferredChain=ISRG Root X1"
```

**Comment by JuanJakobo** [comment]
Cool, thank you!
