### ISSUE TITLE
Pocket Book 624 compatibility

### ISSUE THREAD

**Issue by IlyaER** [JuanJakobo/Pocketbook-Nextcloud-Client#19]
Pocket Book 624 can not start the nextcloud client application.
The screen blinks once and then app list shows

**Comment by JuanJakobo** [comment]
hi,
what firmware are you using? (settings -> software -> softwareversion)

**Comment by IlyaER** [comment]
Its R624.4.4.1740

**Comment by JuanJakobo** [comment]
Great. It might be that the SDK I am using to build the app does not fit for your device. (https://www.pocketbook-int.com/parts-of-software)
Yours is A-13 and I build for B288.
I uploaded a test build for A-13 https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.74.
Could you please try it?

**Comment by IlyaER** [comment]
I've tried, but no success.
The same issue: just blinks screen.

**Comment by JuanJakobo** [comment]
hmm, okay. I am really not sure what is the issue and it is hard to tell from the distance. Could you try https://github.com/JuanJakobo/Pocketbook-HelloWorld/releases/tag/0.1 and tell me what the logs at system/config/HelloWorld do say?

**Comment by IlyaER** [comment]
Well, that is strange as there are no logs created here belonging to HelloWorld application.
The app just blinks screen and nothing else.

**Comment by TiberiusRegenschein** [comment]
I am owning a PB623 and I can confirm the results of IlyaER. No log file created in system/config/

**Comment by JuanJakobo** [comment]
Okay, then the SDK I am using seems not to be working with the PB623, I will have a look into it.

**Comment by JuanJakobo** [comment]
OKay das weird. Where you able to install/use any other custom apps for the PB so I can build the app with that SDK?

**Comment by JuanJakobo** [comment]
No feedback received so I will close this.
@TiberiusRegenschein @IlyaER

**Comment by JuanJakobo** [comment]
No feedback received so I will close this.
@TiberiusRegenschein @IlyaER
