### ISSUE TITLE
Change Path for sync to external sd card

### ISSUE THREAD

**Issue by ReckedOne** [JuanJakobo/Pocketbook-Nextcloud-Client#21]
When you press sync it automatically starts to download content to the internal file system.
Is it possible to change the path where the synched content will be safed e.g the sd card?

**Comment by JuanJakobo** [comment]
Hey, 
thanks for using the tool and sorry for the late answer. It is possible but I am currently a little bit short on time. Once I find the time I will implement it as I also need such a function for the texteditor.
