### ISSUE TITLE
Feature request: please do not clear fields in case of an connection error

### ISSUE THREAD

**Issue by g4c** [JuanJakobo/Pocketbook-Nextcloud-Client#22]
Hi,

Thanks for the wonderful piece of software.
I'd like to ask you for one change (if you could find some time): would it be possible to not clear the fields on the login screen in case of connection error? Especially the one containing the nextcloud's address,

Best regards,
GC

**Comment by JuanJakobo** [comment]
Hi,
I am currently doing a rewrite so sure. I will add that.

Bests,
Juan
