### ISSUE TITLE
Pocketbook-Nextcloud-Client not working with a self-signed SSL certificate (curl error code 60)

### ISSUE THREAD

**Issue by gogoLOPy** [JuanJakobo/Pocketbook-Nextcloud-Client#26]
Hi,

we run our nextcloud on a local-only-server (Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-125-generic x86_64)) with_out_ domainname. Nextcloud was installed via snap and runs like a charm. We use a self-signed SSL certificate generated by:
`root@intserver:~#nextcloud.enable-https self-signed`

Desktop-clients (Kubuntu) and browser-logins just need to grant the exception and the cloud works as expected.
The connection via pocketbook-browser works (without complains about the certificate ... which is a security issue btw)

Nextcloud.app was moved to "applications" folder of our InkPad-X PB1040 (Software: U1040.6.5.2920 (26.7.2022)) and starts up normally.

Pocketbook-Nextcloud-Client throws a "curl error code 60" when we try to login via _https_://192..../
(from man curl: 60     Peer certificate cannot be authenticated with known CA certificates.)

Pocketbook-Nextcloud-Client throws a "curl response code 301" when we try to login via _http_://192..../

what to do?

tx

**Comment by JuanJakobo** [comment]
Hi,
really weird that the Pocketbook-browser does not complain...
Your self-signed SSL cert has the ending ".pem", doesnt it?

**Comment by gogoLOPy** [comment]
jep. The certs (cert.pem, @chain.pem and privkey.pem) are located in /var/snap/nextcloud/~current/certs/self-siged as well as in /var/snap/nextcloud/31222/certs/self-siged.
Maybe --cacert has to be specified or the -k option?

**Comment by JuanJakobo** [comment]
Hi, I drafted a pre release that you can download [here](https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/1.00).
Could you please save your cert on the PB filesystem as  "/system/config/nextcloud/customCert.pem" and have a try?
Thanks!

**Comment by gogoLOPy** [comment]
tried several things, but throws an error 77 (77     Problem with reading the SSL CA cert (path? access rights?).)
the file has -rw-r--r-- (when connected with USB)
```
25/Aug/2022:15:58:15 +0200:Error:An error occured. (Error (Curl Error Code: 60)). Please try again.
25/Aug/2022:15:59:40 +0200:Error:An error occured. (Error (Curl Error Code: 60)). Please try again.
25/Aug/2022:16:00:20 +0200:Error:An error occured. (Error (Curl Error Code: 60)). Please try again.
25/Aug/2022:16:16:37 +0200:Error:An error occured. (Error (Curl Error Code: 60)). Please try again.
25/Aug/2022:16:24:17 +0200:Error:An error occured. (Error (Curl Error Code: 60)). Please try again.
25/Aug/2022:16:24:28 +0200:Info:closed DB
25/Aug/2022:16:24:28 +0200:Info:closed DB
25/Aug/2022:16:25:02 +0200:Info:closed DB
25/Aug/2022:16:25:02 +0200:Info:closed DB
25/Aug/2022:16:53:53 +0200:Error:An error occured. (Error (Curl Error Code: 60)). Please try again.
25/Aug/2022:17:03:49 +0200:Info:closed DB
02/Sep/2022:12:52:06 +0200:Error:An error occured. (Error (Curl Error Code: 60)). Please try again.
02/Sep/2022:12:57:53 +0200:Info:closed DB
02/Sep/2022:13:01:32 +0200:Error:An error occured. (Error (Curl Error Code: 77)). Please try again.
02/Sep/2022:13:11:31 +0200:Error:An error occured. (Error (Curl Error Code: 60)). Please try again.
02/Sep/2022:13:17:19 +0200:Error:An error occured. (Error (Curl Error Code: 77)). Please try again.

```

**Comment by gogoLOPy** [comment]
This command just complains a self signed certificate (this at least indicates, that a self-signed certificate was found)
The -k option works fine and without error.

```
~$ curl -X PROPFIND -H "Depth: 1" -u myuser:MyPasswd https://192.168.4.101/remote.php/dav/files/myuser | xml_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Negative repeat count does nothing at /usr/lib/x86_64-linux-gnu/perl5/5.30/XML/Parser/Expat.pm line 372.

no element found at line 1, column 0, byte 0:

^
 at /usr/lib/x86_64-linux-gnu/perl5/5.30/XML/Parser.pm line 187.
 at /usr/bin/xml_pp line 79.
```

**Comment by JuanJakobo** [comment]
Well the -k option just bypasses the cert check, that one would work, but I do not really want to implement it.
From your example I dont undestand if you ran:
`~$ curl -X PROPFIND -H "Depth: 1" -u myuser:MyPasswd https://192.168.4.101/remote.php/dav/files/myuser | xml_pp`
or 
`~$ curl -X PROPFIND -H "Depth: 1" -u myuser:MyPasswd -CACERT <YourCert>.pem https://192.168.4.101/remote.php/dav/files/myuser | xml_pp`
The cert issue is the same as in the application as far as I can see, so it would be nice if you get the curl working. I cannot really debug from my site and once the curl command above works, it is easy for me to implement it into the application.
I imagine you created your .pem somehow like https://supportportal.juniper.net/s/article/Generate-a-self-signed-SSL-certificate-in-PEM-format-using-OpenSSL?language=en_US this?

**Comment by gogoLOPy** [comment]
specifying the certificate with --cacert cert.pem results in:
curl: (60) SSL: unable to obtain common name from peer certificate
file cert.pem gives cert.pem: PEM certificate
I looked around how to include a "common name" into the cert, but found nothing helpful how that could be done with "nextcloud.enable-https self-signed"

The installation was carried out as described here https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-20-04 

The certificate was generated by following: Step 4, "Option 2: Setting Up SSL with a Self-Signed Certificate"
```sudo nextcloud.enable-https self-signed```
'... The above output indicates that Nextcloud generated and enabled a self-signed certificate.'
Help on that snap-command (https://github.com/nextcloud-snap/nextcloud-snap#included-cli-utilities):

```
sudo nextcloud.enable-https -h
Usage:
    nextcloud.enable-https -h
    Display this help message.

    nextcloud.enable-https <subcommand> [OPTIONS]
    Run the provided subcommand.

Available subcommands:
    lets-encrypt [OPTIONS]
    Obtain a certificate from Let's Encrypt and automatically keep it
    up-to-date.

    self-signed
    Generate and use a self-signed certificate. This is easier to
    setup than Let's Encrypt certificates, but will cause warnings in
    browsers.

    custom [OPTIONS]
    Use certificates generated by other means.
```
... no more details available.

I think, that clients just use "the -k option" in case they encounter a self-signed certificate.

**Comment by JuanJakobo** [comment]
I added a bottom to ignore certs to the login screen. Please have a try. https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/1.01

**Comment by gogoLOPy** [comment]
thanks Juan, it works perfectly!
