### ISSUE TITLE
Feature request - sort by date

### ISSUE THREAD

**Issue by andi-at-1** [JuanJakobo/Pocketbook-Nextcloud-Client#27]
Hello,

Let me first tell you - i love your app, thats a perfect addition to the book!

But i wonder, would it possible to sort the content by date instead of name, like its possible in the nextcloud webui, 'midified'? This would make it much easier to quickly find newly added files.

Thanks for your work!

**Comment by JuanJakobo** [comment]
Hi, I drafted a pre release that you can download [here](https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/1.00). You can select the option in the menu by selecting "Order items by" and then "Last Modified". Does it work as you need it?
