### ISSUE TITLE
Can't login (Curl response code 301)

### ISSUE THREAD

**Issue by MeGreen** [JuanJakobo/Pocketbook-Nextcloud-Client#29]
Hi, i'm using an InkPad Lite with Softwareversion U970.6.5.2897, Nextcloud Version 24.05 and Release 1.02 of this app.

Unfortunately I get "Error (Curl Error Code: 35))" when trying to login, using either https://mydomain oder https://mydomain/remote.php
This happens with either "ignore cert" and without.

Leaving out https:// results in an unknown Curl error code 301

Is there something else i can try, or that you could need to debug?

Thank you very much in advance, for even being so wonderful creating such an app in the first place

**Comment by MeGreen** [comment]
Also, when trying to build the application myself with branch 6.5 from the SDK 6.3.0 i get the error 
`../SDK/SDK-B288/usr/bin/arm-obreey-linux-gnueabi-clang++: line 1: toolchain-wrapper: command not found
`
i guess i'm having something fundamental wrong here?

**Comment by JuanJakobo** [comment]
Hi, 
Without the https your server seems to make an redirect to the https and therefore the 301.
The error 35 says, as you already figured out I guess, unknown SSL Version. What SSL provider are you using?
What happens if you do a normal curl from your machine, does it work? What does it say about SSL? 
 `$ curl -v -X PROPFIND -H "Depth: 1" -u user:pass https://example.com/nextcloud/remote.php/dav/files/USERNAME/ | xml_pp` (https://docs.nextcloud.com/server/20/user_manual/en/files/access_webdav.html#accessing-files-using-curl)

Regarding the SDK error I just tried the 6.5 as I used 5.19 before. For me it seems to work.
What exactly did you do?
Your first executed the update_path.sh?
The error occurs when execute `make`, what else does it say?
I am currently not at my laptop, once I am I will check. :)

**Comment by MeGreen** [comment]
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying IPv6-Adress:443...
* Connected to mydomain.com ([IPv6-Adress) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [88 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [146 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3871 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [111 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=mydomain.com
*  start date: Aug 13 21:08:23 2022 GMT
*  expire date: Nov 11 21:08:22 2022 GMT
*  subjectAltName: host "mydomain.com" matched cert's "mydomain.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Server auth using Basic with user 'user'
* h2h3 [:method: PROPFIND]
* h2h3 [:path: /remote.php/dav/files/PocketBook/]
* h2h3 [:scheme: https]
* h2h3 [:authority: mydomain.com]
* h2h3 [authorization: Basic dXNlcjpwYXNz]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [accept: */*]
* h2h3 [depth: 1]
* Using Stream ID: 1 (easy handle 0x55c9af42ef60)
} [5 bytes data]
> PROPFIND /remote.php/dav/files/PocketBook/ HTTP/2
> Host: mydomain.com
> authorization: Basic dXNlcjpwYXNz
> user-agent: curl/7.85.0
> accept: */*
> depth: 1
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
< HTTP/2 401 
< server: nginx
< date: Sat, 24 Sep 2022 10:06:32 GMT
< content-type: application/xml; charset=utf-8
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< set-cookie: oc_sessionPassphrase=4mFfhWDrG67TNiL8BLIlqvhYWwL%2F4queXJkFtugSBd%2Fl4WVNop5VPNT09OsnriMqhDiHe7dIn3vujyznLj1UEBG59%2BIHHGuEaihhk0ebOZrqmMJPYWJuIVOglPVdvY%2Fy; path=/; secure; HttpOnly; SameSite=Lax
< set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< content-security-policy: default-src 'none';
< set-cookie: ocuu1t5h6ctk=7somgk6480jdrt72v5s1reoudk; path=/; secure; HttpOnly; SameSite=Lax
* Authentication problem. Ignoring this.
< www-authenticate: Basic realm="Nextcloud", charset="UTF-8"
< strict-transport-security: max-age=15768000; includeSubDomains; preload;
< referrer-policy: no-referrer
< x-content-type-options: nosniff
< x-download-options: noopen
< x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
< x-robots-tag: none
< x-xss-protection: 1; mode=block
< 
{ [415 bytes data]
100   415    0   415    0     0    957      0 --:--:-- --:--:-- --:--:--   956
* Connection #0 to host mydomain.com left intact
zsh: command not found: xml_pp
```

This is the output for the command, i just substituted the IPv6 Adress and Domain. I use Let's Encrypt for my Certificates, i hope that is what you mean.
I've already started to suspect that the error is with my server, I've just not been able yet to figure out where and how.

Regarding the building:
In my first attempt i had the SDK and the git repo laying in my Downloads-Folder and modified the TOOLCHAIN_PATH to the relative Path from the downloaded Repo to the SDK. so, assuming the are both in the Downloads-Folder, I used `../SDK/SDK-B288`
As i didn't exactly know what you meant by basic building utils, but i had already built some other git projects and AUR builds, i just assumed i would have the right ones, like gcc, cmake, autoconf etc.
I'm not sure what update_path.sh you mean, where should that be?

In the end, i made a docker with the SKD 6.5 and that somehow worked. I don't know anything about building stuff with extra SDKs, so please forgive me my stupidity.

Thank you very much for your time and effort!

**Comment by JuanJakobo** [comment]
Ah okay, I also use Let's Encrypt. And it seems as the config is similar. If you write me an email to [github@johannsn.com](mailto:github@johannsn.com) I can provide you an test account for my server to verify if it is the server or the device. :)

Regarding the SDK I think the docker solution is the easiest one. When I started to develop for the PB it was unfortunately not available.
If you want to try chaning some curl parameters in the code they are in the file:
https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/blob/master/src/api/webDAV.cpp
and there the functions **propfind** and **get**. 
Propfind loads the folder structure and get is for the Download of items.

The curl part for the Propfind looks like the following --> 

`
        struct curl_slist *headers = NULL;
        headers = curl_slist_append(headers, "Depth: 1");
        curl_easy_setopt(curl, CURLOPT_URL, (_url + pathUrl).c_str());
        curl_easy_setopt(curl, CURLOPT_USERPWD, post.c_str());
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "PROPFIND");
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, Util::writeCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &readBuffer);

        if(_ignoreCert)
        {
            Log::writeInfoLog("Cert ignored");
            curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
            curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
        }

        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "<\?xml version=\"1.0\" encoding=\"UTF-8\"\?> \
                                                    <d:propfind xmlns:d=\"DAV:\"><d:prop xmlns:oc=\"http://owncloud.org/ns\"> \
                                                    <d:getlastmodified/> \
                                                    <d:getcontenttype/> \
                                                    <oc:size/> \
                                                    <d:getetag/> \
                                                    <oc:favorite/> \
                                                    </d:prop></d:propfind>");`
