### ISSUE TITLE
Works on Pocketbook Era / PB700

### ISSUE THREAD

**Issue by jskvbinmv** [JuanJakobo/Pocketbook-Nextcloud-Client#33]
First of all thank you for developing this software! I've just installed it on my Pocketbook Era (PB700) with Firmware Version U700.6.7.1555, and encountered no issues so far.

The only thing is is that the margins on the left and right are very tight. There is no whitespace at all between the text and the bezel of the device. 

Thanks for all your hard work on this project!

**Comment by JuanJakobo** [comment]
Thank you for the warm words! :)
Could you please send a picture of it? Then I can have a look.

**Comment by JuanJakobo** [comment]
I added some margins. Thanks.
