### ISSUE TITLE
Unable to Establish TLS 1.3 Connection - Curl Error 35

### ISSUE THREAD

**Issue by IUCCA** [JuanJakobo/Pocketbook-Nextcloud-Client#37]
Hi,
I'm currently experiencing connection issues with the application, resulting in the error message "Curl error 35." It appears that the application lacks TLS 1.3 support, which may be causing these problems. As a temporary solution, I manually reverted the server to TLS 1.2 to solve the issue.

I'd like to request the addition of TLS 1.3 support to our application to address these connection issues. Before proceeding, could you please confirm whether this feature can be added within the application itself, or if it requires support at the firmware level?

**Comment by JuanJakobo** [comment]
Hi,
currently I am using the local Curl, therefore it is a problem on firmware level. I could also build the binary using a newer version of curl just for this binary. Currently I do not have the time to do so, once I find the time, I will compile this version.

**Comment by JuanJakobo** [comment]
Hi, I finally had a look. I tested with a nextcloud and TLS 1.3 enabled and it worked. It is a bit hard to debug from my side. Could you try to curl the instance using pbterm? That would be helpful.

**Comment by IUCCA** [comment]
Hi,
curling the instance from pbterm was not really helpfull, the verbosed output is: `curl: (35) Peer reports incompatible or unsupported protocol version.
` (PB inkpad 3)
I'm using traefik as proxy with the following options:

```
tls:
  options:
    default:
      minVersion: VersionTLS13
      preferServerCipherSuites: true
      sniStrict: true
```

Curling with a computer:

````
curl https://cloud.example.com -v                                                                                                                                                                
* Host cloud.example.com:443 was resolved.
* IPv6: (none)
* IPv4: 192.168.1.2
*   Trying 192.168.1.2:443...
* Connected to cloud.example.com (192.168.1.2) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_CHACHA20_POLY1305_SHA256 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=example.com
*  start date: Nov 17 15:46:31 2023 GMT
*  expire date: Feb 15 15:46:30 2024 GMT
*  subjectAltName: host "cloud.example.com" matched cert's "*.example.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://cloud.example.com/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: cloud.example.com]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: cloud.example.com
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/2 302 
< cache-control: no-store, no-cache, must-revalidate
< content-security-policy: default-src 'self'; script-src 'self' 'nonce-b3lUWWxXdUQ0Mm1yUVFGcW9obUs4bFVMMmlWdnkyd0VtOHBaRlN6S1g1OD06OEY2LzB6TG5yUkhNZEdrU21sTEF2VFp5bjBZQWhsMHp6cjBkWFVTYU1kUT0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
< content-type: text/html; charset=UTF-8
< date: Tue, 19 Dec 2023 12:56:32 GMT
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< location: https://cloud.example.com/login
< pragma: no-cache
< referrer-policy: no-referrer
< server: nginx
< set-cookie: oc_sessionPassphrase=epG%2FCw1mHdn07utP4pZuMQ5elZ3HLA1M9DwC%2FoaGdJGKxMjqboGP73ievzswsrsFM3f5eLIWZlSVdWH9wiNo7%2FPS5XarWKJdUwej2FAhrlTI3X5jFknPZujmlOO9CH2O; path=/; secure; HttpOnly; SameSite=Lax
< set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< set-cookie: ocwjp1q01eft=fc09135313f1090dd0baae3d5a859d9b; path=/; secure; HttpOnly; SameSite=Lax
< strict-transport-security: max-age=63072000; includeSubDomains; preload
< x-content-type-options: nosniff
< x-download-options: noopen
< x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
< x-robots-tag: noindex, nofollow
< x-xss-protection: 1; mode=block
< 
* Connection #0 to host cloud.example.com left intact
```

**Comment by JuanJakobo** [comment]
Thanks, so it is not the application but the device in total. What version of curl is installed  on your PB inkpad 3?

**Comment by IUCCA** [comment]
The installed version of curl on my PB inkpad 3 is curl 7.82.0, with libcurl/7.82.0, NSS/3.30.2, zlib/1.2.11, and c-ares/1.12.0. This version should support tls1.3. It's worth noting that opening the site via a browser is working.

**Comment by carloscomputer** [comment]
@JuanJakobo I running the application on a PB Color 3 and get the same error as @IUCCA. actually I don't know how to get the curl version information.
I reconfigurated nginx to use tlsv1.3 only but the error occurs.
How can we make progress ? 
Cheers !

**Comment by JuanJakobo** [comment]
Hi,
the problem is that I cannot reproduce it. So either you try to add some log to the app itself and try to debug it by yourself or, if that would be okay for you, provide me with an test account to your nextcloud  via github@johannsn.com and I will try to debug it from my device. (that could take some time through) 
Bests

**Comment by IUCCA** [comment]
@carloscomputer To install the terminal, you need to download [pbterm.zip](http://users.physik.fu-berlin.de/~jtt/), unzip it and simply copy "pterm.app" into the "Applications" directory of your Pocketbook.

@JuanJakobo You should have received an e-mail with a test account

**Comment by carloscomputer** [comment]
@IUCCA i guess the pbterm.zip is moved, the only I can find is his github https://github.com/Alastor27/pbterm
makeakrm.sh faild for now in reason of crosscompiling issues `pbterm/../../FRSCSDK/bin/arm-none-linux-gnueabi-g++: No such file or directory` on mac m1 and lack of virtualized linux.

@JuanJakobo from me you should recieved an e-mail too

**Comment by JuanJakobo** [comment]
okay, I got the mails. Will have a look into it once I have some spare time available.

**Comment by JuanJakobo** [comment]
Hi,
I was able to reproduce the error. I replaced the local libcurl by a newer one from conan and it seems to work now. You have to add cacert.pem to the applications folder. (https://curl.se/ca/cacert.pem)
You can download the release here:
https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/1.12

**Comment by IUCCA** [comment]
Thanks for the new release and take care, it works now

**Comment by dl9msr** [comment]
I can confirm TLS 1.3 works with version Nextcloud 28.0.2 and your release 1.12 on Pocketbook ERA 
I have a Letsencrypt certificate and I get a certificate error.
Is the Letsencrypt CA not supported on Pocketbooks?
I activated the ignore certificate error option and it worked.

**Comment by JuanJakobo** [comment]
Hi,
So the TLS 1.3 works and you can login and then test is separately with the letsencrypt cert?
I am myself using Letsencrypt certs, so it should normally work.
What error msg do you get?

**Comment by dl9msr** [comment]
Hi, thanks for reply.
The error message:
An error occurred. (SSL peer certificate or SSH remote key was not OK (Curl Error Code:60)) Please try again. 
![IMG_0226](https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/assets/47478232/4ce5cc4f-6e63-4a6d-96d7-5e262cc84970)
Ignore certificate permit Poketbook login
Seperatly login is no problem without certificate error. I also use webdav with an other App on IPhone / IPad and Windows 11 PC for sync data.

**Comment by dl9msr** [comment]
Here you can see the certificate is approved and valid
![IMG_0026](https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/assets/47478232/c8afb953-4364-4c93-b686-6c9e2fb57065)

**Comment by JuanJakobo** [comment]
Thats weird. Currently there is no test if the cacerts.pem file is present, but is is required. Did you place it into applications/cacert.pem? (https://curl.se/ca/cacert.pem)

**Comment by dl9msr** [comment]
Thanks Juan,
I'm sorry, I missed that with cacert.pem 
That was the problem. Now it works fine.
