### ISSUE TITLE
no Connection - Curl 302 Error

### ISSUE THREAD

**Issue by Tommy-01** [JuanJakobo/Pocketbook-Nextcloud-Client#38]
When i try to connect to my Nextcloud Instance, i get an unknown Curl 302 Error.

My Nextcloud Version: 27.1.3
It worked with an older Version: 25

**Comment by JuanJakobo** [comment]
Hi,
For me it its working fine on 27.1.4. Therefore it is a bit hard to reproduce. Did you change something else?

**Comment by Tommy-01** [comment]
Yes, i changed my Nextcloud Instance from docker to a LXD Version. Maybe there is a problem. But all other clients are working perfectly with the new LXD Version.

**Comment by JuanJakobo** [comment]
okay. 302 is a redirect. Could you log out, delete your data and try to login again, maybe the path changed party (e.g. from <your-url>/nextcloud/... to <your-url>/... If that does not help, could you send the structure of your url? Are you using CalDav or something where you have to type in your complete Url and does it keep working?

**Comment by Tommy-01** [comment]
I got the problem.
The URL wasn't correct --> `<IP>`
Correct is `https://<IP>` 

Like described in the documentation, sry ;) 
Thanks for your reaction!
Ticket closed
