### ISSUE TITLE
Pocketbook Touch Lux 5 formating 

### ISSUE THREAD

**Issue by ScatteredDrifter** [JuanJakobo/Pocketbook-Nextcloud-Client#4]
Hello, 

I'd like to start and thank you a lot for developing and releasing this app. I always had issues with dropbox on the pocketbook and wished for a nextcloud application as this was my only concern. I've tested it on my Pocketbook touch lux 5 and so far it seems to work pretty well without any profound issue. 
Browsing trough the nextcloud application I have a weird formatting issue with clipping text - to be seen in the screenshot. 
I dont know if it's issued by the different display resolution or something else. 

I dont have much of a problem with it, however I wanted to let you know that it works fine on the touch lux 5 with the recent firmware. 

Thank you a lot!

**Comment by ScatteredDrifter** [comment]
I forgot to send the image, sorry. 

![scr0002](https://user-images.githubusercontent.com/63316422/104300642-08ee6b80-54c7-11eb-9e6d-3f81538d6979.jpg)

**Comment by JuanJakobo** [comment]
Hey @ScatteredDrifter thanks for your feedback. I had it on my agenda but since it resolved fine on my HD 3 I never made the effort to make the font sizes relative. In [release 0.51](https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.51) it should work fine. Would be cool if you can test it and give me a feedback. :)

**Comment by ScatteredDrifter** [comment]
This update fixed it for me, thank you a lot @JuanJakobo. 
Do you plan to implement automated synchronization at some point or is it already included? 
Works pretty well otherwise :). 

Device is a PocketBook Touch Lux 5

**Comment by JuanJakobo** [comment]
@ScatteredDrifter Perfect. Are you talking about selecting an folder and the content of the folder shall be synchronized everytime you open the Application? Or what exactly do you require?

**Comment by ScatteredDrifter** [comment]
Yea something like this basically. 
You can enable certain folders to be synchronized. All files within the particular folder are downloaded, updated, deleted afterwards. It's just erasing the extra steps of download every single file in a folder I want to download. I don't know if its hard to add this function, but if you have the muse and opportunity at sometime I would be grateful. 
Doesn't need to be rushed tho, I'm satisfied with the current version!

**Comment by JuanJakobo** [comment]
@ScatteredDrifter 
I drafted a pre-release including the request. (https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.6) I still had no time to test it a lot, so if you could test it, it would really help. 

Thanks in advance :)
