### ISSUE TITLE
no rescan of database when new files where synced

### ISSUE THREAD

**Issue by TabForce** [JuanJakobo/Pocketbook-Nextcloud-Client#41]
Hi! Is it possible to let pocketbook do a rescan of the database to find freshly synced books? 

Thank you
Ray

**Comment by JuanJakobo** [comment]
Hi, 
you are talking about an rescan in the background or manually by the user?
When you open the app do an long click on the folder you want to sync. A menu will pop-up and you can press "Sync". All the content of the folder will be downloaded and the item will be labeled "Downloaded" instead of "Cloud". Once the folder gets out of sync, the label will change to "structure synced", if you do an long click again, you can select "Sync" an all the changes will be downloaded.
A background check is not possible using this app.
Bests

**Comment by Neogrey** [comment]
> Hi, you are talking about an rescan in the background or manually by the user? When you open the app do an long click on the folder you want to sync. A menu will pop-up and you can press "Sync". All the content of the folder will be downloaded and the item will be labeled "Downloaded" instead of "Cloud". Once the folder gets out of sync, the label will change to "structure synced", if you do an long click again, you can select "Sync" an all the changes will be downloaded. A background check is not possible using this app. Bests

I think he means the database/library of the pocketbook? if you download a book via the Nextcloud app then it doesn't show up directly in the pocketbook library. Only after waking the pocketbook from sleep a refresh of the downloaded books seems to take place and then they appear in the library. At least I have noticed this behavior or am I doing something wrong?.

**Comment by JuanJakobo** [comment]
Ah, that should be possible. I created a pre-release containing this. Could you please test it. https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/1.13. Some installation stuff changed. Please have a look at the Readme.

**Comment by TabForce** [comment]
Neogrey, that's exactly what I ment! Thank you

**Comment by Neogrey** [comment]
> Ah, that should be possible. I created a pre-release containing this. Could you please test it. https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/1.13. Some installation stuff changed. Please have a look at the Readme.

At least for me (InkPad 3 Pro), the behavior is fixed with 1.13. After downloading a book, the Pocketbook library is being refreshed and the book appears directly. Thanks for the fix.

And thanks in general for the Nextcloud app, it's a shame that Pocketbook itself doesn't offer any integration.

**Comment by JuanJakobo** [comment]
Great.
