### ISSUE TITLE
Get no connection

### ISSUE THREAD

**Issue by WST1811** [JuanJakobo/Pocketbook-Nextcloud-Client#7]
Hello,

first, thanks for the Program. ;)
Today i found and try it asap. But no luck, i set the Servername:
https://192.168.178.8 (nothing more, i read your instructions ;) )
or
https://host.domain.tld (nothing more, i read your instructions ;) )
User
and Password klick Login: Loading... and loading... and loading.
WiFi is full available.

Is there a Log or anything else i can check?

Thanks and Regards
Winfried

**Comment by WST1811** [comment]
Sorry, i've vergot the PB Details.
It is a Pocketboot Aqua 2 PB641.

**Comment by JuanJakobo** [comment]
Hey Winfried, 

thanks for testing the program. :)

Is it showing an hourglass? Is the hourglass disappearing?
Normally the Curl should throw an error message if it fails, but this errors are currently not written to the log. I can implement that easily. 
The config file and log files are stored in the folder /system/config/nextcloud.
Are there any files in the folder?

**Comment by WST1811** [comment]
Hi Juan,

in system\config\nextcloud i can find no file.
In this case i wrote you, there was no error. The hourglass was present. Yesterday allways come Offline, at the same time i can surf in Internet at the PB641. The selected structure is not available offline. Of course Wifi is active and Dropbox Sync is running at the same time.
If you can implement to write a log file, i will test again. 
Which format must have the config file? Allways i test i have to write my login + PW for the testaccount and the server URL. If the config file will present, i don't must write it on every try. ;)

Thanks and regards
Winfried

**Comment by WST1811** [comment]
Hi Juan,

is it possible to get an icon in Settings > Accounts an Sync?

**Comment by JuanJakobo** [comment]
So you can login or is it still only showing the login screen?

but the folder system/config/nextcloud exists?
I added some logging and uploaded a pre release (https://github.com/JuanJakobo/Pocketbook-Nextcloud-Client/releases/tag/0.6)
Could you please test it?

Was "The selected structure is not available offline." this the error message? Then the offline modus is activated. It can be changed in the menu.

The config file encrypts the password so you cannot really modify it.

**Comment by JuanJakobo** [comment]
s it possible to get an icon in Settings > Accounts an Sync?
I currently have no idea how to implement that, but I will take a look into it. :)

**Comment by JuanJakobo** [comment]
Just saw your response on mobileread. I have no time today to test it, but will do it in the next days. Thanks :)

**Comment by JuanJakobo** [comment]
Hey Winfried, 

It was an rather simple formating issue.

Your instance:
URL/nextcloud/remote.php/dav/

My instance:

URL/remote.php/dav/files/JuanJJ/

So if you use in the URL field URL/nextcloud it should work.

I will think of an fix for that. 

Thanks for testing. :)

**Comment by WST1811** [comment]
> Your instance:
> URL/nextcloud/remote.php/dav/
> 
> My instance:
> 
> URL/remote.php/dav/
> 
> So if you use in the URL field URL/nextcloud it should work.
> 
> I will think of an fix for that.
> 
> Thanks for testing. :)

Hey Juan!
Thank you very much, you made my Day! :) Its working. :)

Now i go ahead to test and sync further. :)

I don't know how you can fix it, but if you find a fix, everyone can use your App for Nextcloud AND Owncloud. I think Own- and Nextcloud are very close together for synching.

Thanks and regards
Winfried

**Comment by WST1811** [comment]
> is it possible to get an icon in Settings > Accounts an Sync?
> I currently have no idea how to do that, but I will have a look at it. :)

I found in applications\ a dropboxctl.app with this content:

`#!/bin/sh
exec /ebrmain/bin/dropboxctl.app
`
I don't know how to change directory to ebrmanin/bin/, maybe it helps you. It would be nice to have a Icon there, but no must.

Thanks and Regards
Winfried

**Comment by JuanJakobo** [comment]
Good idea. Unfortunately I do not have an nextcloud instance running, but you are correct, it should work. 

I will open a new ticket for the request and see what I can do. Thanks for the request. :)
